apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage
  namespace: homepage
  labels:
    app: homepage
data:
  kubernetes.yaml: |
    mode: cluster
  settings.yaml: |
    title: TS Photoclicks Homepage

    background:
      image: https://cdnb.artstation.com/p/assets/images/images/006/897/659/large/mikael-gustafsson-wallpaper-mikael-gustafsson.jpg
      blur: sm
      saturate: 100
      brightness: 50
      opacity: 100

    color: slate

    useEqualHeights: false

    layout:
      Hypervisor:
        header: true
        style: row
        columns: 4
        useEqualHeights: true
      Containers:
        header: true
        style: row
        columns: 4
      DNS:
        header: true
        style: row
        columns: 4
      Network:
        header: true
        style: row
        columns: 4

  custom.css: ""
  custom.js: ""
  bookmarks.yaml: ""
  services.yaml: |
    - Hypervisor:
        - Proxmox:
            icon: proxmox.svg
            href: "https://pve1.tsphotoclicks.net:8006"
            description: pve1
            # widget:
            #     type: proxmox
            #     url: "{{HOMEPAGE_VAR_PROXMOX_URL}}"
            #     username: "{{HOMEPAGE_VAR_PROXMOX_USER}}"
            #     password: "{{HOMEPAGE_VAR_PROXMOX_API_KEY}}"
            #     node: xing-01

    - Other:
        - GitLab:
            icon: gitlab.svg
            href: https://gitlab.com
            description: source code
        - GitHub:
            icon: github.svg
            href: https://github.com
            description: source code
  widgets.yaml: |
    - resources:
        cpu: true
        memory: true
        disk: /

    - datetime:
        text_size: xl
        format:
          timeStyle: short
  docker.yaml: ""