apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage
  namespace: homepage
  labels:
    app: homepage
data:
  kubernetes.yaml: |
    mode: cluster
  settings.yaml: |
    title: TS Photoclicks Homepage

    background:
      image: https://cdna.artstation.com/p/assets/images/images/051/102/990/large/gioele-muscolino-artstation-post-8.jpg

    theme: dark
    color: slate

    useEqualHeights: true

    layout:
      Hypervisor:
        header: true
        style: row
        columns: 4
      Other:
        header: true
        style: row
        columns: 4
  custom.css: ""
  custom.js: ""
  bookmarks.yaml: ""
  services.yaml: |
    - Hypervisor:
        - Proxmox-1:
            icon: proxmox.svg
            href: "{{HOMEPAGE_VAR_PROXMOX_1_URL}}"
            description: pve1
            widget:
                type: proxmox
                url: "{{HOMEPAGE_VAR_PROXMOX_1_URL}}"
                username: "{{HOMEPAGE_VAR_PROXMOX_USER}}"
                password: "{{HOMEPAGE_VAR_PROXMOX_API_KEY}}"
                node: pve1
        - Proxmox-2:
            icon: proxmox.svg
            href: "{{HOMEPAGE_VAR_PROXMOX_2_URL}}"
            description: pve2
            widget:
                type: proxmox
                url: "{{HOMEPAGE_VAR_PROXMOX_2_URL}}"
                username: "{{HOMEPAGE_VAR_PROXMOX_USER}}"
                password: "{{HOMEPAGE_VAR_PROXMOX_API_KEY}}"
                node: pve2
        - Proxmox-3:
            icon: proxmox.svg
            href: "{{HOMEPAGE_VAR_PROXMOX_3_URL}}"
            description: pve3
            widget:
                type: proxmox
                url: "{{HOMEPAGE_VAR_PROXMOX_3_URL}}"
                username: "{{HOMEPAGE_VAR_PROXMOX_USER}}"
                password: "{{HOMEPAGE_VAR_PROXMOX_API_KEY}}"
                node: pve3
    - Other:
        - GitLab:
            icon: gitlab.svg
            href: https://gitlab.com
            description: source code
  widgets.yaml: |
    - resources:
        cpu: true
        memory: true
        disk: /

    - datetime:
        text_size: xl
        format:
          timeStyle: short
  docker.yaml: ""