apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage
  namespace: homepage
  labels:
    app: homepage
data:
  kubernetes.yaml: |
    mode: cluster
  settings.yaml: |
    title: Techno Tim Homepage

    background:
      image: https://cdnb.artstation.com/p/assets/images/images/006/897/659/large/mikael-gustafsson-wallpaper-mikael-gustafsson.jpg
      blur: sm # sm, md, xl... see https://tailwindcss.com/docs/backdrop-blur
      saturate: 100 # 0, 50, 100... see https://tailwindcss.com/docs/backdrop-saturate
      brightness: 50 # 0, 50, 75... see https://tailwindcss.com/docs/backdrop-brightness
      opacity: 100 # 0-100

    theme: dark
    color: slate

    useEqualHeights: true

    layout:
      Hypervisor:
        header: true
        style: row
        columns: 4
      Other:
        header: true
        style: row
        columns: 4
  custom.css: ""
  custom.js: ""
  bookmarks.yaml: ""
  services.yaml: |
    - Hypervisor:
        - Proxmox:
            icon: proxmox.svg
            href: "https://pve1.tsphotoclicks.net:8006"
            description: pve1
    - Other:
        - GitLab:
            icon: gitlab.svg
            href: https://gitlab.com
            description: source code
        - GitHub:
            icon: github.svg
            href: https://github.com
            description: source code
  widgets.yaml: |
    - resources:
        cpu: true
        memory: true
        disk: /

    - datetime:
        text_size: xl
        format:
          timeStyle: short
  docker.yaml: ""