apiVersion: apps/v1
kind: Deployment
metadata:
  name: homepage
  namespace: homepage
  labels:
    app.kubernetes.io/name: homepage
spec:
  selector:
    matchLabels:
      app: homepage
  replicas: 3
  template:
    metadata:
      labels:
        app: homepage
    spec:
      containers:
      - name: homepage
        image: "ghcr.io/benphelps/homepage:latest"
        ports:
        - containerPort: 3000
