apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: homepage
  namespace: homepage
  annotations:
    gethomepage.dev/href: "https://homepage.k3s.tsphotoclicks.net"
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`homepage.k3s.tsphotoclicks.net`)
      priority: 10
      services:
        - name: homepage
          port: http
  tls:
    secretName: default
