apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: homepage
  namespace: homepage
  annotations:
    gethomepage.dev/href: "https://homepage.k3s.tsphotoclicks.net"
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`homepage.k3s.tsphotoclicks.net`)
      priority: 10
      services:
        - name: homepage
          port: 80
    - kind: Rule
      match: Host(`homepage.k3s.tsphotoclicks.net`) && Headers(`Content-Type`, `application/grpc`)
      priority: 11
      services:
        - kind: Service
          name: homepage
          namespace: homepage
          port: 3000
          scheme: http
          strategy: RoundRobin
          weight: 10
  tls:
    secretName: default