apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: homepage
  namespace: homepage
  annotations:
    gethomepage.dev/href: "https://homepage.k3s.tsphotoclicks.net"
    gethomepage.dev/enabled: "true"
    gethomepage.dev/description: Media Server
    gethomepage.dev/group: Media
    gethomepage.dev/icon: emby.png
    gethomepage.dev/name: Homepage
    gethomepage.dev/widget.type: "emby"
    gethomepage.dev/widget.url: "https://homepage.k3s.tsphotoclicks.net"
    gethomepage.dev/pod-selector: ""
    gethomepage.dev/weight: 10 # optional
    gethomepage.dev/instance: "public" # optional
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`homepage.k3s.tsphotoclicks.net`)
      services:
        - kind: Service
          name: homepage
          namespace: homepage
          port: 8080
          scheme: http
          strategy: RoundRobin
          weight: 10
  tls:
    secretName: default
