apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: redirect-homepage
  namespace: homepage
spec:
  redirectScheme:
    scheme: https
    permanent: true
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: http-homepage
  namespace: homepage
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`homepage.k3s.tsphotoclicks.net`)
      kind: Rule
      services:
        - name: homepage
          port: 3000
      middlewares:
        - name: redirect-homepage
          namespace: homepage
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: https-homepage
  namespace: homepage
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`homepage.k3s.tsphotoclicks.net`)
      kind: Rule
      services:
        - name: homepage
          port: 3000
  tls:
    secretName: default