apiVersion: apps/v1
kind: Deployment
metadata:
  name: terraform-cloud-agent
  namespace: terraform
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tfc-agent
  template:
    metadata:
      labels:
        app: tfc-agent
    spec:
      containers:
      - name: tfc-agent
        image: hashicorp/tfc-agent:latest
        env:
        - name: TFC_AGENT_NAME
          valueFrom:
            secreteKeyRef:
              name: terraform-agent-secret
              key: agent-name

        - name: TFC_AGENT_TOKEN
          valueFrom:
            secreteKeyRef:
              name: terraform-agent-secret
              key: agent-token