apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: certmanager-app-clone
  namespace: argocd
spec:
  project: clone

  source:
    repoURL: https://github.com/torchilidae/k3s-argocd.git
    targetRevision: main
    path: apps/certmanager
  destination: 
    server: https://kubernetes.default.svc
    namespace: certmanager

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true