apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn-app
  namespace: argocd
spec:
  project: storage

  source:
    repoURL: https://charts.longhorn.io/
    chart: longhorn
    targetRevision: v1.8.1
    helm:
      values: |
        preUpgradeChecker:
          jobEnabled: false

  destination:
    server: https://kubernetes.default.svc
    namespace: longhorn-system

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    
    automated:
      selfHeal: true
      prune: true
