apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: certmanager-longhorn
  namespace: longhorn-system
spec:
  secretName: longhorn-cert
  issuerRef:
    name: acme-issuer
    kind: ClusterIssuer
  dnsNames:
    - "*.ltc.tsphotoclicks.net"
