apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token-secret
  namespace: certmanager
spec:
  encryptedData:
    api-token: AgA+iPZjkcsmiiug35aar4xIMzzGrKZSGeXdMtxDVxc6p3gU9/keeaFDDlnKHFHuwHcG5HtJoAPk0tg/iGgLJ29rZ4+gc4qpPiUqevdMGh/ql9IuEHBrOkspQTqRnY3SOuyGpw7pf1boKHARhbRdO8y7BTtk/wiMQEIKTPCqLM3vtSsy9LCv2gQ1WlcHw3wVNRviVZzwpaam2nEAtqJVYSSY8Be4Zb8b1a+yaGqp1RRq/c6dS4Dj5TaGlf1qEz+6GD0MKEkCsH8C1gdIDBNtAhfBotYa+9t9VpHBksf3IjvWZCMREbtAiOYb9+uR2s33o0D2zeeMKQmq32nTb+hbaP231KAQvIvJbYoxzm0w7c3d9dmhLmmFFZaWGQ4hll4dj4Qj8977v+idXSD4HdPmaVZ4rKfqK+qS+ohbQTEXSmWkGJgrshPmWpQJ3UwflTcwgJQh8PkqISk8xPOvTOqT51oHMiJP9eo+YTCRiRSQiCJ3vVC0WWfI/60MdVXNWK0yQ/L+EvUthvnqaDITQc3O75T2s6T9fecTCvlXONYumyQAJPHhQYchpO3wlm+j8G/Nd/fqiDYFpJwVIX9fC9rtRwSXarq5XfET7OVL21voti6eTBYBWfvHCgugM0HWZycXthYKlqB5FNIZ6pJDlxhULq4KI286+ME4JXCf5uPoVweJudaynEy727r1JnV79JtllHx8zpvrcdpUdFOTd6l9lWE7/ziDMM9yxwpzQuCnlqwd9Tz9beubgZLf
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-token-secret
      namespace: certmanager
    type: Opaque
