apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealedsecret-app
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://bitnami-labs.github.io/sealed-secrets
    chart: sealed-secrets
    targetRevision: v2.14.2
    helm:
      parameters:
        - name: installCRDs
          value: "true"

  destination: 
    server: https://kubernetes.default.svc
    namespace: security

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true