apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: uptimekuma-app
  namespace: argocd
spec:
  project: monitor

  source:
    repoURL: https://github.com/torchilidae/k3s-argocd.git
    targetRevision: main
    path: monitor/uptimekuma

  destination:
    server: https://kubernetes.default.svc
    namespace: monitor

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    
    automated:
      selfHeal: true
      prune: true
