apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: certmanager-uptimekuma
  namespace: uptimekuma
spec:
  secretName: uptimekuma-cert
  issuerRef:
    name: acme-issuer
    kind: ClusterIssuer
  dnsNames:
    - "*.ltc.tsphotoclicks.net"
