apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: redirect-uptimekuma
  namespace: uptimekuma-system
spec:
  redirectScheme:
    scheme: https
    permanent: true
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: http-uptimekuma
  namespace: uptimekuma-system
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`uptimekuma.ltc.tsphotoclicks.net`)
      kind: Rule
      services:
        - name: uptimekuma-frontend
          port: 80
      middlewares:
        - name: redirect-uptimekuma
          namespace: uptimekuma-system
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: https-uptimekuma
  namespace: uptimekuma-system
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`uptimekuma.ltc.tsphotoclicks.net`)
      services:
        - name: uptimekuma-frontend
          port: 80
  tls:
    secretName: uptimekuma-cert