apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: redirect-hello-world
spec:
  redirectScheme:
    scheme: https
    permanent: true
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: http-hello-world
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`nginx.k3s.tsphotoclicks.net`)
      kind: Rule
      services:
        - name: hello-world
          port: 80
      middlewares:
        - name: redirect-hello-world
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: https-hello-world
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`nginx.k3s.tsphotoclicks.net`)
      kind: Rule
      services:
        - name: hello-world
          port: 80
  tls:
    secretName: default