---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token-secret
  namespace: sealedsecret
spec:
  encryptedData:
    api-token: AgB9RL0pC0A+j9uwwWz7eeASHtWJrHGzQVgXWpVYv15WLiVht9dLrRbMS985/2gfSKUknaMMcRH3Mudijv5331f3EXeBLWg0iQ4vBvmDg2bp6zeoLFgzek68eFK3FiRs3whr6qrGC9yEtUYCES5pyFBPwFzA88VPDXUR+cpWZm5jMg+KDnGqBvlJ82NEOkXeD+YWHaQnbuoDXpE18R0JwBSqVfBPuKtlzBVHPU/NvdIjrKtRO4ShvRjOd8fDiJpymWv/xHS0eKsIDVTrQdaFHqeo3OVEJEfbmGDAonc7zAd5vQyO2X5/XswsU0vUeWK3aPByCq8Jm7jv6A5hJXmoiC6WRLuNS2MZpcsoPmD9LHZ1rQitzNQkVeakwGTiJSgCDUNN2uLw6l+qeafI8w02fjUWuMuqDXVHTY/osZ5IL4Mz70mUHALeW8u/Kd1Z+zGBCJgt7X6pGF0YLmuWhsR6ZMYeAvCTiwJVvdIayMJlDQQy40StflYwbEcafCLJglpZf1BfbZmCpKzZwkxIG1CT/cH6VQ5lVomVGPYXHry802utQMsNxm5I1hAj/gBYc7if2qYLffiW6RvxSSL0PLoTf/z7IlHsSXA9zxf+k+aKWozGqsuolu4GKwooLTNRyw5kGLvvp+MgwhR2tEgxtftZ1k2CubwRO8Krpty4A3MIspG9HyOkxtdIQZMtpfb5yci1Cy2Ww33igZQP+4z6uSS8IzLUwtMw/5IfsnahOkDOrlY2y3YVz3zfWJRH
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-token-secret
      namespace: certmanager
    type: Opaque
