apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: reloader-app
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://stakater.github.io/stakater-charts
    chart: reloader
    targetRevision: HEAD

  destination: 
    server: https://kubernetes.default.svc
    namespace: reloader

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true