apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: certmanager-argocd
  namespace: argocd
spec:
  secretName: argocd-cert
  issuerRef:
    name: acme-issuer
    kind: ClusterIssuer
  dnsNames:
    - "*.k3s.tsphotoclicks.net"
